version: '3.8'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached
      - gohome:/home/vscode/go:cached
    environment:
      PATH: ${PATH}:/workspace:/usr/local/go/bin:/home/vscode/go/bin
      GOPATH: /home/vscode/go
      HF_DATASETS_CACHE: /workspace/.cache/huggingface
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ "gpu" ]
    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    env_file: 
      - .env
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)
volumes:
  gohome:
